### ISSUE TITLE
Comicvine Search Results issues

### ISSUE THREAD

**Issue by jdinda70** [comictagger/comictagger#143]
Running 1.2.0+2 Develop Branch on Windows

2 issues:

1.

When I search for: "Spider-Man" in the Series it returns the 1990 volume of Spider-Man from Comicvine, but not the 2016 or 2019 volumes of Spider-Man (of course along with a bunch of other volumes with Spider-Man in the name).

They are returned via the comic vine website when I search and restrict the search to "Volumes".

Searching for "Spider" or "Man" separately also does not return the 2016 or 2019 volumes.

2.

When I search for "X-Men" in the series it does not return ANY with just the volume name "X-Men" from ComicVine (there are 24 volumes total, 4 from Marvel: 1991, 2004, 2010, & 2013)

They are returned via the comic vine website when I search and restrict the search to "Volumes".

Searching for "X" or "Men" separately also does not return these volumes.

There maybe other similar issues, but these are two i have seen recently.

**Comment by davide-romanini** [comment]
Seems related to #112. 
Currently I'm trying to stabilize and automate the build and release process. After that I hope to have a better base to test and fix all these issues.

**Comment by beville** [comment]
Just looked into it, and this is the result of aggressive pruning of search results.  Last year's change to Comic Vine's search required some changes to keep  the amount of results from being too overwhelming.  The fact that the results are sorted according some undefined 'relevance' algorithm is helpful. 

The fetching is stopped when any of a few criteria are matched.  One is if the number of words in the result volume name is greater than the original request, plus a fixed threshold, which is hard-coded at 3 (named as "result_word_count_max"). This idea was a shot in the dark, but has seemed to work pretty well so far.

The code in question is in "searchForSeries()" in comicvinetalker.py

I found two simple (but maybe not perfect) ways to handle this:

1) Use the patch in #138 to allow more results per fetch (from 10 (default) to 100).

 2) Increase or allow the user to configure the threshold that is used to calculate result_word_count_max

And less simple: 

3) Rework the result-limiting algorithm in searchForSeries().  I think that CV Scraper plugin for ComicRack did something quite different, but I can't remember what.

Regardless, I still recommend upping the search result limit since it reduces the number of hits to Comic Vine's API.

**Comment by jdinda70** [comment]
Guys ... thanks for looking into this.  Don't stress.  It would be great to find a solution at some point but it sounds like it's a challenging issue.  Thanks for pointing out the file/function where this code is. I don't know anything about Python, but I'll see if I can figure it out.

**Comment by dadino** [comment]
We could use a new field, similar to "Specify series search string for all selected archives", that allow us to set the ID of the ComicVine volume. 
I'm using ComicTagger to tag comics in folders (by volume), one folder at a time, so this would speed up search significantly and make it much more stable (because at that point you're just looking for the issue number in the filename/existing tags).

**Comment by jdinda70** [comment]
FYI.  In 1.3.0-alpha.0 (2019-10-06), these particular issues are resolved. Closing issue.
