### ISSUE TITLE
Cannot launch comictagger

### ISSUE THREAD

**Issue by apastuszak** [comictagger/comictagger#174]
Whenever I try to install and run ComicTagger on Linux using the provided instructions, I always get the following error:

`ImportError: cannot import name 'ctversion' from 'comictaggerlib' (/home/andy/comictagger/comictaggerlib/__init__.py)`

**Comment by apastuszak** [comment]
Ok, I fixed the issue by installing from pip.  But now I get a new error:

Cannot mix incompatible Qt library (5.14.1) with this library (5.15.0)

**Comment by musictrivianut** [comment]
I am running into something similar after upgrading to Ubuntu 20.04 Focal Fossa.  At this point, PyQT4 is no longer installed (or supported, if I understand correctly) and the GUI definitely won't run because of that, although it says it will do CLI mode.

Any thoughts from anyone on how to fix this?

**Comment by musictrivianut** [comment]
Well, like @apastuszak, I managed to get mine installed correctly from pip.  Just had to switch to pip3.  One of these days I will figure all of this out.

**Comment by lordwelch** [comment]
pip3 is now listed in the README install instructions.
