### ISSUE TITLE
New initiative on Comic book metadata

### ISSUE THREAD

**Issue by gotson** [comictagger/comictagger#178]
Hi,

i'm the developper of https://komga.org/, and recently started an initiative to discuss the various issues around Comic book metadata. The project is located here: https://github.com/anansi-project/rfcs

Someone [on Reddit](https://www.reddit.com/r/comicrackusers/comments/i70g55/comicrack_metadata_a_legacy/g11ox34?utm_source=share&utm_medium=web2x) suggested that we should include you in the discussion, given Comic Tagger is pretty big in this space. So that's a ping to @davide-romanini :)

Feel free to join the discussions!

**Comment by davide-romanini** [comment]
Hi @gotson,

Thank you for your contribution. For various reasons I had little time to dedicate to comictagger, although I still have several ideas for future evolution. I also started a prototype project written in Rust similar to komga (and also comicstreamer and ubooquity). I didn't release it yet, because it's just very embrional and limited. The problem I have with java based projects, is that on my own little NAS they are just too heavyweight. Rust instead is extremely light and fast. Maybe it will not be more a problem when I'll change my NAS..

Keep up the hard work 👍

**Comment by gotson** [comment]
The Java ecosystem brings a lot of useful frameworks and libraries, but indeed the ram usage is usually quite high. I used to have a low-end NAS running lots of things, i upgraded to a NUC and now uses the NAS only for storage.

**Comment by uniquename** [comment]
...runs smoothly on a pi 4 2gb;-)

+1 for unifying standards!

**Comment by gotson** [comment]
Hi @davide-romanini ,

we recently brought a new initiative under the Anansi Project's umbrella, we are now steering evolutions of the `ComicInfo.xml` schema!

You can find more information in the [repo](https://github.com/anansi-project/comicinfo) as well as on the [website](https://anansi-project.github.io/).

We would be very happy to have ComicTagger as a [supporter of the initiative](https://github.com/anansi-project/comicinfo#whos-behind-this) ! If you are in, you could submit a simple PR to add ComicTagger in the README (like https://github.com/anansi-project/comicinfo/pull/9).

**Comment by lordwelch** [comment]
Hi @gotson,
At least for the moment I'm the active maintainer for ComicTagger, I'm looking over the repo now and it looks like a good start, just a note the discord link on the website is broken anansi-project/anansi-project.github.io#1.
