### ISSUE TITLE
Default issuenumber to 01 if field is empty

### ISSUE THREAD

**Issue by jfml** [comictagger/comictagger#182]
Not sure if this is an edge case since I mostly have European comics / graphic novels but it happens to me a lot that I manage to find the correct album but then a get a „Could not find an issue for that series“ popup since I forgot to fill the issue-field with 01, so I have to get back, do that, search again.

**Comment by rhaussmann** [comment]
Was there a reason not to have issue 1 as a default? Maybe a concern it would return too many results?

**Comment by jfml** [comment]
Since my other main issue just got resolved can I bump this again, I still have a problem with constantly +___+

**Comment by lordwelch** [comment]
I don't really want to make the issue number default to 01 as there is no way to do a sanity check or calculation to confirm or even estimate as to what the issue number would be, as even OCR would only work in the best case.
ComicTagger has several ways to get around this.

Example: The Vigilant
<img width="1102" alt="Screen Shot 2022-06-07 at 9 11 44 PM" src="https://user-images.githubusercontent.com/7547075/172531058-31732708-e09a-4371-8725-4d74d5fa66a2.png">

Instead of clicking `OK` click `Show Issues`.
<img width="1119" alt="Screen Shot 2022-06-07 at 9 12 02 PM" src="https://user-images.githubusercontent.com/7547075/172531063-0780c58e-d20c-459e-88f7-b025b0803a51.png">

The specific issue can then be selected from the list.
<img width="984" alt="Screen Shot 2022-06-07 at 9 30 03 PM" src="https://user-images.githubusercontent.com/7547075/172532168-b1de89f1-10e1-4ed6-aa18-2cb35ac55b8a.png">

You can also use the `Auto-Tag` function and select the `If no issue number, assume "1"` check box.
<img width="624" alt="Screen Shot 2022-06-07 at 9 13 04 PM" src="https://user-images.githubusercontent.com/7547075/172531068-b26b2430-53a9-4e1c-a77e-d022c9c247e3.png">

If you are using the CLI you can pass the `-1` option (along with `-o -t cr -f` to search online save ComicRack tags and parse the filename) which is the same as running the `Auto-Tag` function in the GUI or you can specify an issue number directly using the '-m' option e.g. `-m=issue=42`

**Comment by jfml** [comment]
Hi! Thanks for the detailed answer, I did not think about American comics just starting at issue number 1 again for the lolz, that complicates things, obviously.

I was not aware of the autotag-feature (even though the button is right there), that is so cool, I'll check that out for sure.
