### ISSUE TITLE
Error opening file  beguining with "["

### ISSUE THREAD

**Issue by aajj68** [comictagger/comictagger#222]
Sample [Author] - Serie #Numer - Title (Tag, Tag, Tag) (English)
Fails when execute comictagger .exe "[Author] - Serie #Number - Title (Tag, Tag, Tag) (English)"
Works in file without "[": "Author - Serie #Number - Title (Tag, Tag, Tag) (English)"
Works too: "(Author) - Serie #Number - Title (Tag, Tag, Tag) (English)"

**Comment by lordwelch** [comment]
Didn't know this before but ComicTagger does it's own globbing on files passed through on the command line specifically for windows, so that `[0].zip` becomes `0.zip` this however only happens when it is an argument so as a workaround you can either open it in the gui or open the folder the file is in

**Comment by lordwelch** [comment]
There is now an explicit option to enable globing `-g, --glob` so by default these filenames will now work,
added in #306
