### ISSUE TITLE
MacOS Binary Crashes When Saving Tags

### ISSUE THREAD

**Issue by tacotruffles** [comictagger/comictagger#223]
MacOS 1.3.0 (2022-02-21) release crashes when saving tags. Was able to circumvent most crashes by replacing some characters I found to be outside of UTF-8 and ASCII character sets in the Notes/Comments field and accented characters in Credits entries:

1. `’` with ASCII-friendly `'` 
2. `ú` to `u`
3. `—` to `-`

However this doesn't always work....maybe there are more characters that are crashing the app in other fields? I wasn't able to find any in the other tag fields. Wondering if there is a character encoding issue with the language the app was compiled in vs what the OS it is running on?

**Comment by lordwelch** [comment]
Well when trying to re-produce the issue I got it to crash once but it won't crash any more and so there's not much I can do right now.
also a nitpick UTF-8 is an encoding of unicode which all of these characters are defined in, these characters are only outside of ASCII.

**Comment by msarrowette** [comment]
I'm seeing the same issue with MacOS version 1.3.0. Only seems to happen with the ComicRack tags, so it's possibly somehow related to the xml file insert? I had reverted to version 1.2.3, which was successfully able to save tags to all my problem files, but as of a day or two ago that has started reporting "Could not connect to Comic Vine to search for series!" so is no use any more. (API key is fine, and works in both ComicTagger 1.3.0 and YACReaderLibrary.)

I don't know if it's any use for you to know specific ComicVine data that's triggering the issue, but here are a few of the comics I've had crashes with:

Daredevil (2019) #10, 16, 17 - all for George Fornés, saving is fine if I change é to e.
Daredevil (2019) #34 - David López, again ó to o saves okay
Daredevil (2019) #20 - some combination of smart ", ' or ...
Daredevil (2019) #36 - em dash

At the moment I'm copying and pasting the content of the notes/comments field to a text editor and doing global replaces on all of the suspect characters I've found before pasting it back, but I'd say that it's crashing about 50% of the time on the set of comics I'm working on at the moment, and like @tacotruffles there are some issues where I just haven't been able to identify the cause. I've had to retype at least one comment entirely from scratch in order to get it to work, and the successful end result didn't look any different to what I started with.

I have also created the XML by hand myself, and it can read it okay, but crashes if I then try to re-save the CR tags.

I can also save successfully before pulling the data down from ComicVine, so it's definitely the data rather than the .cbz file that's causing the crash.

I hope that helps in identifying the cause!

**Comment by tacotruffles** [comment]
@msarrowette Thanks for digging deeper. To confirm what you've found...I didn't make much fuss over this when I downgraded to version 1.2.3...but now that version is saying that my API key is in valid and refuses to connect to Comic Vine.

With version 1.3.0...it still connects fine but the CR tag crash on write issue is still something to deal with. I've also found that in the Credits section...if any of the names have an accented character CR crashes...so not only in the comments but also replacing characters in any names with an unaccented character has been a pretty much the workaround I've been using to keep 1.3.0 from crashing. Not fun when tagging an entire series but for now I can at least tag new releases as they come in.

**Comment by lordwelch** [comment]
@tacotruffles @msarrowette
Found the cause of this. I accidentally left a print statement in for testing.
macOS does not set any locale environment variables when launching a .app from finder which makes Python default to ascii. Then to make things even more complicated Terminal sets those variables making it very annoying to track down.

As a work around, until I figure out how to make python import statements to do what I want, you can run `open /path/to/ComicTagger.app` from the terminal app and run an auto-tag with all of your comics or run `/path/to/ComicTagger.app/Contents/MacOS/comictagger -R -o -t CR -s /folder/with/comics` and either should work

**Comment by lordwelch** [comment]
can either of you verify that the build here works normally?
https://github.com/comictagger/comictagger/actions/runs/2011348073

**Comment by prequelguess** [comment]
@lordwelch I've also been having issues with these crashes & can confirm that this new build runs through all of my previously problematic files I had with no issue at all.

**Comment by msarrowette** [comment]
@lordwelch - Don't have much time to do extensive testing today, but I've wiped tags, re-pulled data from ComicVine, and retagged all the comics I used as examples, as well as a number of others I was having crashes with and hadn't fixed, and all now save OK. New build is working for me. Thanks!

**Comment by tacotruffles** [comment]
@lordwelch Thanks for the command line instructions. Working!

Very much appreciated!
