### ISSUE TITLE
Crashing when images in subfolder

### ISSUE THREAD

**Issue by TheRonGDD** [comictagger/comictagger#242]
Program is crashing when tagging archives that have images in a folder inside archive. This was not the case on previous build. Opening cbr files previously tagged with comictagger and attempting to update metadata is causing crash.

**Comment by lordwelch** [comment]
I can't reproduce this.
What OS are you running ComicTagger on?
Are you using the binary from the release page?
You indicate that you are using cbr files, have you verified that has the correct paths setup for the rar executable and can open other rar files?

**Comment by TheRonGDD** [comment]
WinServer2019
I am using [ComicTagger-1.3.1-win-AMD64.exe.zip]
Yes, other rar files are working fine. I have not updated winrar in a few years. I will try that later and report back if it resolves the issue. 
I am extracting and recompressing them with a batch now. I only have 100 or so files left to tag. I will hold one problem file back for testing.

**Comment by lordwelch** [comment]
Hello, I just published a new [alpha release](https://github.com/comictagger/comictagger/releases/tag/1.3.2-alpha.3) could you try using it? It will probably still fail but it will generate a log file at `%APPDATA%\ComicTagger\logs\ComicTagger.log` that I would like you to upload.
Note: the log file gets rotated on startup so you may end up uploading `%APPDATA%\ComicTagger\logs\ComicTagger.log.1` or another file

**Comment by TheRonGDD** [comment]
I should have mentioned the files are successfully tagged. The program crashes after it finishes. Subsequent attempts to open the tagged file cause the program to crash immediately. If i remove the xml from inside the file i can again load the file, scrape, and tag; comictagger again crashes. Now with this alpa after tagging the archive the xml is created in the file, but now comictagger will not load after it crashes. Removing or renaming the %APPDATA%\ComicTagger directory resolves this new issue. Also a new development related to removing the appdata directory: opening the previously tagged archive that still contains the xml file works as expected.  Comictagger loads the metadata from the archive, and I can edit and save it without a crash. 

Side note: Why are so many fields red? Is this an indication of the underlying issue?
EDIT: I just noticed it was defaulting back to comic lover. That is the reason for the red, and the lack of crashes. I am now testing more with comic rack tags. I changed it back to comic rack made an edit and it crashed. I will do more testing.

![image](https://user-images.githubusercontent.com/19981887/161780024-987272b6-bd9d-4d5a-baf4-d482d7c2a840.png)

Before removing the appdata folder
![image](https://user-images.githubusercontent.com/19981887/161781440-55f9de12-d376-45e5-a548-47a66006b688.png)

After starting comictagger again and editing metadata on the problem archive there are only 2 files settings and the log file. The log is the same as the log from when it crashed. I pasted the complete log here.

To me, the logs appear to not show the issue.

2022-04-05T10:20:28 | comictagger | INFO | ComicTagger Version: 1.3.2a2 running on: Windows PyInstaller: Yes
2022-04-05T10:20:28 | comictagger | DEBUG | Installed Packages
2022-04-05T10:20:28 | comictagger | DEBUG | altgraph	0.17.2
2022-04-05T10:20:28 | comictagger | DEBUG | pycountry	22.3.5
2022-04-05T10:20:28 | comictagger | DEBUG | pyinstaller	4.10
2022-04-05T10:20:28 | comictagger | DEBUG | setuptools	58.1.0
2022-04-05T10:20:28 | comictagger | DEBUG | wheel	0.37.1

**Comment by lordwelch** [comment]
Yes in the 1.3.2-alpha.2 release I didn't check it very well, it errors when trying to create a logs folder if it already exists. I fixed it in the new alpha release [1.3.2-alpha.3](https://github.com/comictagger/comictagger/releases/tag/1.3.2-alpha.3).

This appears to be a segfault (memory is accessed improperly) from what I'm seeing, but I don't know what would be causing it.

You mentioned that removing the ComicTagger folder in appdata fixed your original issue as well. Do you have a copy of the original folder that you would be willing to send? Also has the issue happened again since removing the folder in appdata?

**Comment by TheRonGDD** [comment]
When i accidentally tagged the files as CBL it still crashes. Removing the  ComicTagger  folder in APPDATA appeared to resolve the issue. If the files were tagged as CR it does not resolve the issue. IT would still crash if I tagged a file that i previously had issues with. Removing the appdata folder appeared to resolve the issue, and allowed me to update the xml in the archive. Again this was as CBL.



Nothing is changed on my end. All I said in my previous post was me not noticing comictagger defaulted back to CBL. Also, I was assuming the crash was caused by the trouble file being in the cache, and not due to the log file being there as you discovered as the issue.

**Comment by lordwelch** [comment]
I found out where the issue happened. Unfortunately any comic archives that crash can only be fixed by manually editing or removing the ComicInfo.xml. The latest alpha release [1.3.2-alpha.4](https://github.com/comictagger/comictagger/releases/tag/1.3.2-alpha.4) has this fix merged

<details>
  <summary>Technical details</summary>

I explicitly set the encoding to utf-8 and enabled generating the xml_declaration
```py
ET.tostring(tree.getroot(), encoding="utf-8", xml_declaration=True)
```
This normally should not have posed any issues as this function returns a byte-string, then the byte-string is immediately decoded into a standard unicode-string which again does not normally pose any issues. The issue occurs when we open a temporary file for text writing, when we do that Python automatically decides the encoding to use and will convert the unicode-string to the encoding that it decides. On windows the default encoding is cp1252 which is an extension of ASCII that is in-compatible with Unicode.
The error happens when the file is read back into ComicTagger, ComicTagger gets a byte-string which is given to the xml processor the xml processor starts reading and assumes ASCII and/or cp1252 (the default encoding on windows) until it finds the xml declaration which explicitly states utf-8 and then reads any further data as utf-8
```xml
<?xml version='1.0' encoding='utf-8'?>
```
This issue did not occur with zip files as instead of opening a temporary file as the [writestr](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.writestr) method is used which explicitly encodes the given string as unicode.

To fix files that are encoded incorrectly either remove the entire ComicInfo.xml or change the encoding on the xml files to cp1252
```xml
<?xml version='1.0' encoding='cp1252'?>
```
</details>
