### ISSUE TITLE
Comictagger crashing when autotagging

### ISSUE THREAD

**Issue by Bazzu85** [comictagger/comictagger#287]
Hi, comictagger v1.4.3.
![image](https://user-images.githubusercontent.com/7345587/166108043-44eb7be3-938c-4bd1-b81b-9974320eb8aa.png)

When auto tagging something with this enabled
![image](https://user-images.githubusercontent.com/7345587/166108057-9f1f2e23-aba6-48fa-8673-406bc1a30182.png)

after the tagging if no issues remains in list this error happens:
![image](https://user-images.githubusercontent.com/7345587/166108003-b459b840-6a3e-42b4-a96a-7ff7a90589ab.png)

making the app crash

**Comment by Bazzu85** [comment]
Just tested the 1.4.4.dev11 for the other issue and this one is still there..

**Comment by lordwelch** [comment]
Could you attach the logs from `%APPDATA%\ComicTagger\logs`?

**Comment by lordwelch** [comment]
FYI this issue was probably created when I tried to fix #187

**Comment by Bazzu85** [comment]
Hi, do you still need the logs?

another question, but offtopic..I registered to the forum with Topit'it but the activation mail didn't arrived (registered on 15 march). 
Can I open an issue somewhere? thx

**Comment by lordwelch** [comment]
No I found where the issue was, I have a build on pull request #292 for you the test. [download instructions]

I'm not sure the last time that forum was used... a better option would probably be to use the [discussions] tab

[discussions]: https://github.com/comictagger/comictagger/discussions
[download instructions]: https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests
