### ISSUE TITLE
Community rating causes crash

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#314]
If you've set a community rating for comicinfo.xml it'll cause an exception. taggerwindow.py expects a float. I did the following to fix it for me, change taggerwindow.py:812 from:
```
self.dsbCommunityRating.setValue(md.community_rating or 0.0)
```
to:
```
self.dsbCommunityRating.setValue(float(md.community_rating) or 0.0)
```

**Comment by mizaki** [comment]
Ignore the "fix", I didn't test it without a rating. 

Would changing utils.xlate to include a float option be best?

**Comment by lordwelch** [comment]
Your fix was close, it should have been:
```python
self.dsbCommunityRating.setValue(float(md.community_rating or 0.0))
```
However I think it would actually be bettor to just remove the field in the UI, no metadata formats that I know of have both a user rating and a community rating, so they could just be merged

**Comment by mizaki** [comment]
So close, yet so far! :)

You would think they'd be synonymous. I did notice that if you use ComicBookLover format you can enter both. I couldn't find much on the CBL format after a quick search though. ComicInfo added community rating in version 2 looking at the Anansi project. I can imagine the user rating being a personal rating as opposed to the community aggregate. How much use both are though...

**Comment by lordwelch** [comment]
Though CBL let's you enter it, it does not save it. The control was not added to the list to be disabled.

**Comment by lordwelch** [comment]
Oh, and if you thought that simplified anything you would unfortunately be mistaken.

The metadata scheme is taken from [ComicRack] which did publish schemas for their Metadata however they actually export more than they stated and so the `Day`, `CommunityRating`, `Review`, `MainCharacterOrTeam` elements and the `bookmark` page attribute are all exported but never published in a schema. Since ComicRack was discontinued the Anansi project has tried to continue updating the standard which includes documenting what ComicRack exports but never documented.

The [ComicRack Manual] shows that it supported both kinds of ratings but in practice it only exported the community rating.

Also though storing it as a float would be the correct way to store it, even for CBL it is stored as a string, however on the few resources I found I believe it should be an integer and JSON has separate syntax for integers meaning that we already store it incorrectly...

[ComicRack]: https://web.archive.org/web/20180926062727/http://comicrack.cyolito.com/downloads

[ComicRack Manual]: https://sites.google.com/site/comicrackmanual/chapter-07-managing/fileless-ecomics

**Comment by mizaki** [comment]
That's makes things as clear as mud. 

I suppose it comes down to interoperability? People are still using ComicRack (I just switched away to Komga. YAC gave me problems)? Is the idea to not have ComicRack (and some others) error/crash? Should it not be expected of the newer programs to "just handle it"? CBL obviously get to decide their format but wouldn't adhering to Anansi push that project forward? I think it may already be an issue so going a bit off topic there.

**Comment by lordwelch** [comment]
Just storing it as a string all the time will make sure it is forwards compatible and doesn't have any issue reading the data, it just makes it possible to also write something that is not backwards compatible and would make it so no metadata would be parsed in ComicRack

**Comment by lordwelch** [comment]
So I actually went with adding an is_float parameter to utils.xlate in my first attempt on #319
If you have some time do you think you could check with your comics that this works
The pull request has binary packages that you can use to test, download [instructions]

[instructions]: https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests

**Comment by mizaki** [comment]
I checked out the PR and tested. It appears to work fine. I used my script to generate the comicinfo.xml and it loaded without issue. I then changed the score via the UI and saved and reload, fine again. I tested with a 0 in community field. I tested with text in the field. Finally, tested without the field.

All looks good to me.

**Comment by lordwelch** [comment]
Thanks for testing! #319 is now merged
