### ISSUE TITLE
Alt cover search

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#324]
Found this while working on the DB. I was using "The Uncanny x-men 510" as my test filename.

comicvinetalker:780
```
if url_list is not None:
```
An empty list is always not None. https://towardsdatascience.com/python-the-boolean-confusion-f7fc5288f0ce
```
if url_list:
```
It does equal False though. I did notice sometimes it would stick with the searching message but I don't know if that was some oddity due to debugging.

**Comment by lordwelch** [comment]
Because things are complicated it ends up calling this which has a length check so still shouldn't do anything.
The function call right above on [line 779] used to be able to return null so that's why it's still there.

[line 779]: https://github.com/comictagger/comictagger/blob/68efcc74fbc192395125d98a194451908b8153ec/comictaggerlib/comicvinetalker.py#L779
https://github.com/comictagger/comictagger/blob/68efcc74fbc192395125d98a194451908b8153ec/comictaggerlib/coverimagewidget.py#L217-L221
