### ISSUE TITLE
Problem with names with Special Characters

### ISSUE THREAD

**Issue by Rougecarlos** [comictagger/comictagger#368]
I have a lot of manga with the cover is named by !cover.png because this special character is on of the first in name sorting.

But in comictagger when the name have ! or #, and maybe other characters, is not listed.

**Comment by lordwelch** [comment]
It looks like the sorting algorithm currently puts it at the end of the list, so instead of it being the first item it shows as the last item.
I'll have to experiment with sorting to see if I can fix it.

**Comment by lordwelch** [comment]
@Rougecarlos
This is fixed in the latest release [1.5.0]
If you are on linux you will need to make sure [pyicu] is installed, if you are on Windows or macOS you can use the pre-built apps attached to the release.

[1.5.0]: https://github.com/comictagger/comictagger/releases/tag/1.5.0
[pyicu]: https://pypi.org/project/PyICU/
