### ISSUE TITLE
Multiple files read-only, unable to edit metatags, admin doesn't resolve access issues

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#38]
_From [gonzoke...@gmail.com](https://code.google.com/u/104185397291472572815/) on January 14, 2014 09:22:50_

What steps will reproduce the problem? 1.Select any of the methods for tag info 2. 3. What is the expected output? What do you see instead? Tag info updated to archive What version of the product are you using? On what operating system? wWin7 x64 Please provide any additional information below. Random files and folders are now acting as read-only, while in the properties window of said files/folders, the selection box is blued out, rather than ticked. While I can find the relevant tag info, I cannot update the archive, as the save option is not available. It has occurred with both old and new files, but I cannot identify any particular common factor which is causing this. I've tried running cmd.prompt and changing attributes for the particular folders which have been affected, but after I change the values, they just return to read only. Anything I might have missed?

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=38_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 22, 2014 12:12:14_

Is this still an issue?  Sorry for slow response...

**Comment by davide-romanini** [comment]
_From [gonzoke...@gmail.com](https://code.google.com/u/104185397291472572815/) on March 22, 2014 15:25:56_

No problem. Yeah It seems to be an issue with Win7 and your software, It
stems from folders being in a read-only by default. Whereas other programs
seem ignore that, comictagger doesn't. I am using a program called "take
ownership" to get around the problem at present.

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 23, 2014 19:49:03_

Hmmm. CT has is pretty careful about checking permissions, as it's a more common issue on the UNIX platforms like Linux and Mac OS.  It will decide that a file is not writable for a number of reasons including checking permission on the folder and the file itself.   

I've not heard of anyone else having this issue.  I wonder if your problems stem from having moved files from one account to another on a Windows machine?

If I'm reading this right, you're saying that the folders are marked as read-only, but the files are not?

**Comment by MugenEnzan** [comment]
Hello. I didn't know whether to open a new issue or just comment here, so here I am.

I have the exact same issue, but I am running Kubuntu 19.10. I first assumed it is because my files are stored on an NTFS drive, but when I copied them to my desktop, the issue persisted. It simply doesn't allow me to save, and the file name is tailed with (read only). I attached a screenshot so you can see.

If you require any info or details, please let me know.

Thanks for an awesome utility!!

![Read Only](https://user-images.githubusercontent.com/56924250/78550161-43c2c500-780c-11ea-9584-28588aba955a.png)

Edit: I forcibly took ownership using CHOWN and its still the same. The screenshot is from when I copied it to my desktop, which is formatted as ext4.

**Comment by milesdm** [comment]
I just found ComicTagger, and it appears I'm having a similar issue on Windows 10, and no work around has helped.
I first found an old beta of 1.10, before I realized newer versions were on github, and grabbed 1.2.3 (and 1.3.0 as well as a test), and all files I open show up as read only. I've tried running as admin, take ownership, and nothing seems to resolve it.   Interestingly enough, 1.10 actually looks like it's opening them as editable, however it won't connect to comicvine, so poop. (probably an API change since then)  This happened on my C drive (NTFS) and an SDCard (exFat) on my Surface Pro.

**Comment by hackbot1337** [comment]
yes, this problem sucks! this issue makes CT useless. can anyone please help? using comictagger 1.3.0 on windows 10.

**Comment by jwmcdermaid** [comment]
I only see this happen with CBR, I convert everything to CBZ and have no issue. I don’t know if this is the case for you, but that’s what I do.

On Feb 23, 2021, at 11:51 AM, hackbot1337 <notifications@github.com> wrote:

﻿

yes, this problem sucks! this issue makes CT useless. can anyone please help? using comictagger 1.3.0 on windows 10.

**Comment by ianwday** [comment]
Hey all,

Sorry to be so late getting back this one but I just got around to reinstalling ComicTagger and had the same problem with CBRs.

Go to File-Settings
RAR Tools tab
Click the WINRar link, download, and install WINRar
Click on the 3 dots to locate the WINRar executable (usually C:/Program Files/WinRAR/Rar.exe)
Click OK and restart ComicTagger

![image](https://user-images.githubusercontent.com/59399078/123268891-74a02000-d4cc-11eb-868b-1dbbd3d7337d.png)

Hope this helps!

**Comment by lordwelch** [comment]
This is resolved in a3e1153.
There is now a popup if a CBR/RAR archive is opened and the rar application is not available
