### ISSUE TITLE
Unhandled exeption 

### ISSUE THREAD

**Issue by IDontKnow218** [comictagger/comictagger#400]
I get this error everytime I try to open Comic Tagger:

![image](https://user-images.githubusercontent.com/72819892/204055102-ffa3f1e7-2796-47b4-af77-2bcec06649dd.png)

Is there any way to fix this?

**Comment by lordwelch** [comment]
@IDontKnow218 can you download the latest release here https://github.com/comictagger/comictagger/releases/tag/1.5.4 and test again if it still doesn't work can you scroll to the top of the window and take a screenshot

**Comment by IDontKnow218** [comment]
> @IDontKnow218 can you download the latest release here https://github.com/comictagger/comictagger/releases/tag/1.5.4 and test again if it still doesn't work can you scroll to the top of the window and take a screenshot

@lordwelch I tried with the latest release and same problem appears. I can't take a screenshot because it closes automatically after I open it and the error appears.

**Comment by lordwelch** [comment]
What OS are you on?
If there is a log in `%APPDATA%\ComicTagger\logs` can you attach it

I need you to run ComicTagger in cmd.exe

Go to where you downloaded ComicTagger-1.5.4-win-AMD64.exe instead of running it you are going to hold shift and right-click and select "Copy as path" https://www.howtogeek.com/670447/how-to-copy-the-full-path-of-a-file-on-windows-10/.
Next open cmd.exe click the icon at the top of the window and select paste
![paste](https://kb.froglogic.com/squish/howto/copy-paste-cmd-exe/cmd_system_menu_mark_copy_paste.png)

Then press enter, you should then be able to scroll to the top and take a screenshot

**Comment by IDontKnow218** [comment]
[logs.zip](https://github.com/comictagger/comictagger/files/10095751/logs.zip)
[cmd.txt](https://github.com/comictagger/comictagger/files/10095752/cmd.txt)
  I just copied what's on the window to cmd.txt if that's okay. @lordwelch

**Comment by lordwelch** [comment]
I don't know what happened but your settings file got corrupted delete the whole folder `%APPDATA%\ComicTagger` and you should be back in business

**Comment by lordwelch** [comment]
@IDontKnow218 Did deleting the `%APPDATA%\ComicTagger` folder work?
