### ISSUE TITLE
Is there a ctversion.py file?

### ISSUE THREAD

**Issue by rhaussmann** [comictagger/comictagger#407]
... if there is, I can't see it. 
 
I'm getting a `ImportError: cannot import name 'ctversion' from 'comictaggerlib'`  error after loading up comictagger 1.5.5 and upgrading to python 1.10. There were some` pyicu` issues I resolved before I got stuck on this error. It looks the similar to [Issue #267](https://github.com/comictagger/comictagger/issues/267). I installed py7rz manually to be sure.  Could it be another OSX issue?

**Comment by lordwelch** [comment]
No, you must install ComicTagger. If you are not actively developing ComicTagger I suggest the .app from releases, if for some reason you need ComicTagger via python use PyPi via pip `pip install comictagger[GUI]`. If you just want to install the latest from git, pre-built binaries are available for 30 days since the last commit, click on the checkmark shown in the screenshot below and then follow the rest of the instructions here https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests
<img width="400" alt="Screenshot 2022-12-01 at 2 06 49 PM" src="https://user-images.githubusercontent.com/7547075/205169403-d2d5894a-b309-47fe-bfc6-37ec58c9db01.png">
if you for some reason you need the latest git installed via python use `pip install git+https://øgithub.com/comictagger/comictagger[GUI]`. If you are actually doing development, from the comictagger directory use `pip install -e .[GUI]`

**Comment by rhaussmann** [comment]
Thanks! I'll download from the pull request.
(or just RTFM on the bottom of the readme page...)
