### ISSUE TITLE
OSError on Auto Tagging - Cannot write CMYK as PNG

### ISSUE THREAD

**Issue by falo2k** [comictagger/comictagger#409]
I've run into this over a few issues from Humble Bundles.  When attempting to auto-tag I get the unhandled exception as per the screenshot, and comictagger closes.

![image](https://user-images.githubusercontent.com/1392563/205887333-a6c82cd0-3e04-4650-a479-3d0113c8277d.png)

All images in the file are jpg.  The first two pages (cover and inside cover) are double pages with one blank page, and it looks like the failure is in the attempt to resize that page for checking.

![image](https://user-images.githubusercontent.com/1392563/205887655-88911aad-f4fe-4c9e-aa98-25508edee88f.png)

I've attached three test files, each including one of the first three pages to illustrate.  The first two fail, the last succeeds, so it doesn't appear to be inherent to the image files themselves (assuming all were created in the same way when the original file was packaged).
[Test Files.zip](https://github.com/comictagger/comictagger/files/10165354/Test.Files.zip)

**Comment by lordwelch** [comment]
So you were correct on most points, the only reason the third file doesn't fail is because ComicTagger doesn't need to crop it. If you want this to work on the current version all you need to do is crop out the empty whitespace.

The latest commit will fix this, I plan on doing a pre-release later this week until then you can get a Windows build following these instructions.

Click on the checkmark shown in the screenshot below and then follow the rest of the instructions here https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests
<img width="400" alt="Screenshot 2022-12-01 at 2 06 49 PM" src="https://user-images.githubusercontent.com/7547075/205169403-d2d5894a-b309-47fe-bfc6-37ec58c9db01.png">

**Comment by falo2k** [comment]
Cheers.  Latest build does indeed solve it.  BTW, I also grabbed the build from the PR for the settings rework to have a look and noticed that the formatting for the publisher filter in settings seems to have changed to one per line, but the tooltip still describes it as comma separated.

**Comment by lordwelch** [comment]
> Cheers. Latest build does indeed solve it. BTW, I also grabbed the build from the PR for the settings rework to have a look and noticed that the formatting for the publisher filter in settings seems to have changed to one per line, but the tooltip still describes it as comma separated.

Awesome thanks for letting me know!
