### ISSUE TITLE
CBZ files corrupted after tagging

### ISSUE THREAD

**Issue by Gfurst** [comictagger/comictagger#461]
Just a simple option that instead rewriting the archive with the metadata, just save the xml outside with the same archive name or something. I know this probably wont have an application for most cases, but its something you should be able to do in case you to main the original file intact.

Also, I don't know if its an bigger issue, but some of the files were reported corrupted when I tried to open them, at the time I just restored the files via torrent. but I could look into it again.

**Comment by lordwelch** [comment]
If they were reported as corrupt there's not much I can do. Both rar and zip/unzip have options for attempting to recover a corrupt file.

There are not any programs that will read metadata not in the archive. If you want to manage metadata without altering the archive ComicRack does not save metadata to the archive by default, you can also use either Komga or Kavita, which allows you to save metadata to their internal database without modifying the archive.

I do not intend to support saving external metadata. I do intend on making plugins for metadata providers so someone could potentially create a plugin to do that in the future.

**Comment by Gfurst** [comment]
I was unsure if the metadata inside the archive was the standard, still, I think you misunderstood, the reason I thought of that is because the archive was left in a corrupt state after adding the meta with this program. I just confirmed it again by finding some left over files last week, I couldn't open the archive with either a proper archiver or Mcomix which works with cbz files. Might be worth looking into.

**Comment by lordwelch** [comment]
This is the _only_ report that I have seen claiming that ComicTagger is corrupting comic archives.
If you could please provide the log file for when you believe ComicTagger corrupted:

version 1.5.5 and earlier:
Windows: `C:\Users\<username>\AppData\Roaming\ComicTagger`
MacOS and Linux: `~/.ComicTagger`

any pre-releases after 1.5.5:
MacOS: `~/Library/Logs/ComicTagger`
Windows: `C:\Users\<username>\AppData\Local\ComicTagger`
Linux: `~/.cache/ComicTagger`

I will also need a copy of the _valid uncorrupted_ archive before being processed by ComicTagger and the _invalid corrupted_ archive emailed to me at timmy@narnian.us so I can determine how this corruption happened.

I will also need to know what steps you took. If you used the command line, the exact command used. If you used the GUI what operation you used (eg auto-tag) and what options you set <img width="665" alt="Screen Shot 2022-05-19 at 7 04 04 PM" src="https://user-images.githubusercontent.com/7547075/169434326-ce4888c1-2050-4c67-9eb9-84bc349e5fb1.png">

ComicTagger has existed since [2012] and I have not seen any issues regarding file corruption.

[2012]: https://code.google.com/archive/p/comictagger/

**Comment by Gfurst** [comment]
Ok, this a big log, the first time I've used the tagger so there was a lot of fumbling around. I'll try to get the corrupted files again.

[ComicTagger.culprit.log](https://github.com/comictagger/comictagger/files/11468583/ComicTagger.culprit.log)

**Comment by lordwelch** [comment]
If anyone finds an instance of ComicTagger corrupting a cbz file please open a new issue and please keep a copy around so that I can investigate the issue.

Unfortunately there is nothing in the log provided to determine what may have caused the corruption. Current alpha releases of ComicTagger have more logging enabled and may help in determining the cause of any corruption if it happens again.
