### ISSUE TITLE
No "Tagged with ComicTagger" in notes if overwrite metadata is True

### ISSUE THREAD

**Issue by bbtufty** [comictagger/comictagger#470]
If you have overwrite metadata on when tagging comics, it doesn't add the "Tagged with ComicTagger" part in the notes. This is an issue for e.g. Mylar3, which parses comics from this line of the metadata

**Comment by lordwelch** [comment]
Thanks for the issue @bbtufty!
Unless there is extra data that you specifically want to remove you can omit `--overwrite` instead, this will revert to the behavior in 1.4.3 and before, note `--no-overwrite` will skip any comics that have tags at all and is not the reverse of `--overwrite`.
You can also do two passes one with `--overwrite` which will use the information in the existing tags to search and then a second pass without it which will ensure that the notes section is set properly.
This will be fixed shortly but a new release is not planned in the near future (an alpha release will probably come before the end of June). Yes overwriting metadata currently (in 1.5.5 and 1.6.0-alpha.4) has 3+ options making it needlessly complicated and needs to be fixed. This happened in d55d75cd7949727dedccf8aed6ca6c895ff8e34a when fixing #390 also related to mylar. So using version [1.5.4] instead of 1.5.5 may also be an option.

[1.5.4]: https://github.com/comictagger/comictagger/releases/tag/1.5.4

**Comment by bbtufty** [comment]
Indeed, what I'm doing now is a two-pass thing where I'll quickly tag things with CT to import to mylar just to get enough info, then a second overwriting pass with the CT fork in mylar to get consistent tagging across the series. A little inelegant but it works
