### ISSUE TITLE
Allow blurring images on the pages tab to stop spoilers

### ISSUE THREAD

**Issue by Mock1** [comictagger/comictagger#637]
I am so stoked to find this project alive after all these years!
I am also a metadata-obsessed nerd. I am digging the page types concept, but finding it impossible at scale.
I can't set the type of multiple pages at once (shift-select, etc.), and while I can use the keyboard, I also basically just flipped through the entire book setting 98% of the pages to Story...
Could there be a setting to just go ahead and mark all the pages after the first, as Story by default? Then I only need to check for pages to delete, or previews, editorials/roundups? (Until I give up and stop caring about those, probably).
Dream state would also be some spoiler mode, that blurs the Story pages by default, so you don't get some dramatic reveal spoiled in the last frame, just checking if there is an ad/tag at the end of the book.

**Comment by lordwelch** [comment]
I'm not going to default pages to any type except for the cover because that's needed for other operations.
Now there is already an algorithm to try and determine if there is a scanner page that I can add an option for.
I also will enable bulk edits for page type and the double page checkbox.
I won't be adding in image blurring but if someone wants to make a PR I'm open to it.

**Comment by lordwelch** [comment]
787f3e8ea149b5be4abc3f47d0e631ab3997e101 enables bulk editing for page type and the double page checkbox
d98f815ce00ba56fd002dd6688718548242f1455 Adds a button to attempt to identify a scanner page
These will be included in the next alpha

If anyone wants to contribute a PR to allow blurring out pages I'll accept it.
